import React, { createContext, useContext, useState, useEffect } from 'react'
import type { ReactNode } from 'react'

export type Language = 'tr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isEnglish: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Ana çeviri veritabanı
const translations: { [key: string]: { [key: string]: string } } = {
  tr: {
    // Ana sayfa
    'Anketlerinizi AI ile Güçlendirin': 'Anketlerinizi AI ile Güçlendirin',
    'Profesyonel anket oluşturucu ile benzersiz sorular hazırlayın, trend analizi yapın ve daha fazla yanıt alın.': 'Profesyonel anket oluşturucu ile benzersiz sorular hazırlayın, trend analizi yapın ve daha fazla yanıt alın.',
    'Şablonlar': 'Şablonlar',
    'Trendler': 'Trendler',
    'Yeni bir form hazırlamaya başlayın': 'Yeni bir form hazırlamaya başlayın',
    'Boş Form': 'Boş Form',
    'Sıfırdan yeni bir form oluşturun': 'Sıfırdan yeni bir form oluşturun',
    'AI Destekli': 'AI Destekli',
    'AI Oluşturucu': 'AI Oluşturucu',
    'Yapay zeka ile otomatik oluşturun': 'Yapay zeka ile otomatik oluşturun',
    'Akıllı Öneriler': 'Akıllı Öneriler',
    'Hazır şablonlar ile hızlıca başlayın': 'Hazır şablonlar ile hızlıca başlayın',
    'Kullan': 'Kullan',
    'Popüler': 'Popüler',
    'Kolay': 'Kolay',
    'Orta': 'Orta',
    'Zor': 'Zor',
    '2 dk': '2 dk',
    '3 dk': '3 dk',
    '4 dk': '4 dk',
    '5 dk': '5 dk',
    'İletişim Bilgileri': 'İletişim Bilgileri',
    'Etkinlik LCV Formu': 'Etkinlik LCV Formu',
    'Parti Davetiyesi': 'Parti Davetiyesi',
    'Tişört İstek Formu': 'Tişört İstek Formu',
    'Etkinlik Kayıt Formu': 'Etkinlik Kayıt Formu',
    
    // Navbar
    'Ana Sayfa': 'Ana Sayfa',
    'Anketlerim': 'Anketlerim',
    'Yeni Anket': 'Yeni Anket',

    'Çıkış Yap': 'Çıkış Yap',
    'Kayıt Ol': 'Kayıt Ol',
    'Giriş Yap': 'Giriş Yap',
    'Formlar': 'Formlar',
    'Takvim': 'Takvim',
    'Bugün': 'Bugün',
    'Yarın': 'Yarın',
    'Henüz etkinlik yok': 'Henüz etkinlik yok',
    'Yeni Etkinlik Ekle': 'Yeni Etkinlik Ekle',
    'Etkinlik Adı': 'Etkinlik Adı',
    'Etkinlik adını girin': 'Etkinlik adını girin',
    'Tarih': 'Tarih',
    'Başlangıç Saati': 'Başlangıç Saati',
    'Bitiş Saati': 'Bitiş Saati',
    'Açıklama': 'Açıklama',
    'Etkinlik açıklaması': 'Etkinlik açıklaması',
    'İptal': 'İptal',
    'Etkinlik Ekle': 'Etkinlik Ekle',
    
    // Ayarlar
    'Ayarlar': 'Ayarlar',
    'Genel': 'Genel',
    'Bildirimler': 'Bildirimler',
    'Gizlilik': 'Gizlilik',
    'Güvenlik': 'Güvenlik',
    'Profil Bilgileri': 'Profil Bilgileri',
    'Ad': 'Ad',
    'Soyad': 'Soyad',
    'E-posta': 'E-posta',
    'Bildirim Ayarları': 'Bildirim Ayarları',
    'E-posta Bildirimleri': 'E-posta Bildirimleri',
    'Form yanıtları ve güncellemeler için': 'Form yanıtları ve güncellemeler için',
    'Haftalık Raporlar': 'Haftalık Raporlar',
    'Form performans özetleri': 'Form performans özetleri',
    'Gizlilik Ayarları': 'Gizlilik Ayarları',
    'Veri Analizi': 'Veri Analizi',
    'Anonim kullanım verilerini topla': 'Anonim kullanım verilerini topla',
    'Üçüncü Taraf Entegrasyonları': 'Üçüncü Taraf Entegrasyonları',
    'Jira, Trello gibi servisler': 'Jira, Trello gibi servisler',
    'Güvenlik Ayarları': 'Güvenlik Ayarları',
    'Şifre Değiştir': 'Şifre Değiştir',
    'Mevcut şifre': 'Mevcut şifre',
    'Yeni şifre': 'Yeni şifre',
    'Yeni şifre (tekrar)': 'Yeni şifre (tekrar)',
    'Şifreyi Güncelle': 'Şifreyi Güncelle',
    'İki Faktörlü Doğrulama': 'İki Faktörlü Doğrulama',
    'Ek güvenlik için SMS veya uygulama kodu': 'Ek güvenlik için SMS veya uygulama kodu',
    'Değişiklikleri Kaydet': 'Değişiklikleri Kaydet',
    'Hesabı Sil': 'Hesabı Sil',
    'Kaydediliyor...': 'Kaydediliyor...',
    
    // Admin
    'Admin': 'Admin',
    'Admin E-posta': 'Admin E-posta',
    'Admin Şifre': 'Admin Şifre',
    'Admin Girişi': 'Admin Girişi',
    'Admin Girişi Yapılıyor...': 'Admin Girişi Yapılıyor...',
            'Admin girişi başarısız! E-posta veya şifre hatalı.': 'Admin girişi başarısız! E-posta veya şifre hatalı.',
        'Loglar': 'Loglar',
    'Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.': 'Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.',
    
    // Form Builder
    'Form Oluşturucu': 'Form Oluşturucu',
    'Form Builder': 'Form Oluşturucu',
    'Form Başlığı': 'Form Başlığı',
    'Form açıklaması': 'Form açıklaması',
    'Form description...': 'Form açıklaması...',
    'Form title...': 'Form başlığı...',
    'Soru Ekle': 'Soru Ekle',
    'Question Types': 'Soru Tipleri',
    'Add your first question': 'İlk sorunuzu ekleyin',
    'Start by selecting one of the question types on the left': 'Soldaki soru tiplerinden birini seçerek başlayın',
    'Survey Image': 'Anket Resmi',
    'Saving...': 'Kaydediliyor...',
    'Form title is required': 'Form başlığı gerekli',
    'Form Ayarları': 'Form Ayarları',
    'Durum': 'Durum',
    'Etiketler': 'Etiketler',
    'Yeni etiket ekle...': 'Yeni etiket ekle...',
    'Ekle': 'Ekle',
    'Anonim yanıtlara izin ver': 'Anonim yanıtlara izin ver',
    'İlerleme çubuğunu göster': 'İlerleme çubuğunu göster',
    'Çoklu yanıtlara izin ver': 'Çoklu yanıtlara izin ver',
    'Formu yayınlayın': 'Formu yayınlayın',
    'Katılımcılar': 'Katılımcılar',
    'Bağlantıya sahip olan herkes': 'Bağlantıya sahip olan herkes',
    'Kopyalandı': 'Kopyalandı',
    'Form Önizleme': 'Form Önizleme',
    'Henüz soru eklenmemiş': 'Henüz soru eklenmemiş',
    'Yanıtınızı yazın...': 'Yanıtınızı yazın...',
    'Seçenek seçin...': 'Seçenek seçin...',
    
    // Question Types
    'Short Answer': 'Kısa Metin',
    'Paragraph': 'Uzun Metin',
    'Multiple Choice': 'Tek Seçim',
    'Multiple Select': 'Çoklu Seçim',
    'Dropdown List': 'Açılır Liste',
    'Rating': 'Derecelendirme',
    'Date Question': 'Tarih',
    'Location': 'Konum',
    'Phone': 'Telefon',
    'Email Question': 'E-posta',
    'Full Name': 'Ad Soyad',
    
    // Auth
    'Beni Hatırla': 'Beni Hatırla',
    'Şifremi Unuttum': 'Şifremi Unuttum',
    'Hesabınız yok mu?': 'Hesabınız yok mu?',
    'Zaten hesabınız var mı?': 'Zaten hesabınız var mı?',
    'Şifre (tekrar)': 'Şifre (tekrar)',
    'Şifreler eşleşmiyor!': 'Şifreler eşleşmiyor!',
    'Şifreler eşleşmiyor': 'Şifreler eşleşmiyor',
    
    // Login/Register specific
    'login': 'GİRİŞ YAP',
    'signup': 'KAYIT OL',
    'email': 'E-posta Adresi',
    'emailPlaceholder': 'E-posta adresinizi girin',
    'password': 'Şifre',
    'passwordPlaceholder': 'Şifrenizi girin',
    'loggingIn': 'Giriş Yapılıyor...',
    'or': 'veya',
    'googleLogin': 'GOOGLE İLE GİRİŞ YAP',
    'trelloLogin': 'TRELLO İLE GİRİŞ YAP',
    'jiraLogin': 'JIRA İLE GİRİŞ YAP',
    'personalInfo': 'Kişisel Bilgiler',
    'name': 'Ad',
    'namePlaceholder': 'Adınızı girin',
    'surname': 'Soyad',
    'surnamePlaceholder': 'Soyadınızı girin',
    'age': 'Yaş',
    'agePlaceholder': 'Yaşınızı girin',
    'passwordConfirm': 'Şifre Tekrarı',
    'passwordConfirmPlaceholder': 'Şifrenizi tekrar girin',
    'passwordsMatch': 'Şifreler eşleşiyor',
    'passwordsDoNotMatch': 'Şifreler eşleşmiyor',
    'passwordMinLength': 'En az 8 karakter',
    'passwordAtLeastOneNumber': 'En az 1 rakam',
    'passwordAtLeastOneSpecialChar': 'En az 1 özel karakter',
    'addressInfo': 'Adres Bilgileri',
    'city': 'Şehir',
    'selectCity': 'Şehir seçin',
    'district': 'İlçe',
    'selectDistrict': 'İlçe seçin',
    'bucakNahiye': 'Bucak/Nahiye',
    'selectBucakNahiye': 'Bucak/Nahiye seçin',
    'neighbourhood': 'Mahalle',
    'selectNeighbourhood': 'Mahalle seçin',
    'detailedAddress': 'Detaylı Adres',
    'addressDetailsPlaceholder': 'Sokak, bina no, kat, daire no vb. detayları girin',
    'creatingAccount': 'Hesap Oluşturuluyor...',
    'createAccount': 'HESAP OLUŞTUR',
    'forgotPassword': 'Şifremi Unuttum',
    'alreadyHaveAccount': 'Zaten hesabınız var mı?',
    
    // Common
    'Yükleniyor...': 'Yükleniyor...',
    'Hata': 'Hata',
    'Başarılı': 'Başarılı',
    'Uyarı': 'Uyarı',
    'Bilgi': 'Bilgi',
    'Tamam': 'Tamam',
    'Kapat': 'Kapat',
    'Evet': 'Evet',
    'Hayır': 'Hayır',
    'Sil': 'Sil',
    'Düzenle': 'Düzenle',
    'Kopyala': 'Kopyala',
    'Paylaş': 'Paylaş',
    'İndir': 'İndir',
    'Yazdır': 'Yazdır',
    'Ara': 'Ara',
    'Filtrele': 'Filtrele',
    'Sırala': 'Sırala',
    'Temizle': 'Temizle',
    'Uygula': 'Uygula',
    'Sıfırla': 'Sıfırla',
    'Geri': 'Geri',
    'İleri': 'İleri',
    'Son': 'Son',
    'İlk': 'İlk',
    'Önceki': 'Önceki',
    'Sonraki': 'Sonraki',
    'Sayfa': 'Sayfa',
    'Toplam': 'Toplam',
    'Göster': 'Göster',
    'Kayıt': 'Kayıt',
    'Saat': 'Saat',
    'Tip': 'Tip',
    'Detay': 'Detay',
    'Özet': 'Özet',
    'Rapor': 'Rapor',
    'İstatistik': 'İstatistik',
    'Grafik': 'Grafik',
    'Tablo': 'Tablo',
    'Liste': 'Liste',
    'Grid': 'Grid',
    'Kart': 'Kart',
    'Modal': 'Modal',
    'Dropdown': 'Dropdown',
    'Tooltip': 'Tooltip',
    'Alert': 'Alert',
    'Notification': 'Notification',
    'Toast': 'Toast',
    'Badge': 'Badge',
    'Avatar': 'Avatar',
    'Button': 'Button',
    'Input': 'Input',
    'Select': 'Select',
    'Checkbox': 'Checkbox',
    'Radio': 'Radio',
    'Switch': 'Switch',
    'Slider': 'Slider',
    'Progress': 'Progress',
    'Spinner': 'Spinner',
    'Skeleton': 'Skeleton',
    'Divider': 'Divider',
    'Space': 'Space',
    'Row': 'Row',
    'Col': 'Col',
    'Container': 'Container',
    'Header': 'Header',
    'Footer': 'Footer',
    'Sidebar': 'Sidebar',
    'Content': 'Content',
    'Main': 'Main',
    'Section': 'Section',
    'Article': 'Article',
    'Aside': 'Aside',
    'Nav': 'Nav',
    'Menu': 'Menu',
    'Breadcrumb': 'Breadcrumb',
    'Pagination': 'Pagination',
    'Steps': 'Steps',
    'Tabs': 'Tabs',
    'Accordion': 'Accordion',
    'Collapse': 'Collapse',
    'Timeline': 'Timeline',
    'Tree': 'Tree',
    'Transfer': 'Transfer',
    'Upload': 'Upload',
    'Rate': 'Rate',
    'ColorPicker': 'ColorPicker',
    'DatePicker': 'DatePicker',
    'TimePicker': 'TimePicker',
    'Calendar': 'Calendar',
    'Form': 'Form',
    'Table': 'Table',
    'List': 'List',
    'Layout': 'Layout',
    'Navigation': 'Navigation',
    'Feedback': 'Feedback',
    'Data Entry': 'Data Entry',
    'Data Display': 'Data Display',
    'General': 'General',
    'Other': 'Other',
    
    // Forms sayfası
    'My Forms': 'Anketlerim',
    'Anket yönetimi ve takibi': 'Anket yönetimi ve takibi',
    'Anket ara...': 'Anket ara...',
    'Yenile': 'Yenile',
    'Survey': 'Anket',
    'Status': 'Durum',
    'Category': 'Kategori',
    'Responses': 'Yanıtlar',
    'Last Update': 'Son Güncelleme',
    'Actions': 'İşlemler',
    // Durum metinlerinin İngilizce anahtar eşlemesi
    'Active': 'Aktif',
    'Draft': 'Taslak',
    'Archived': 'Arşivlenmiş',
    'Unknown': 'Bilinmiyor',
    'Aktif': 'Aktif',
    'Taslak': 'Taslak',
    'Arşivlenmiş': 'Arşivlenmiş',
    'Bilinmiyor': 'Bilinmiyor',
    'Ürün': 'Ürün',
    'Müşteri': 'Müşteri',
    'İnsan Kaynakları': 'İnsan Kaynakları',
    'Eğitim': 'Eğitim',
    'Pazarlama': 'Pazarlama',
    'Teknoloji': 'Teknoloji',
    'Yanıt': 'Yanıt',
    'Görüntü': 'Görüntü',
    'Tamamlanma': 'Tamamlanma',
    'soru': 'soru',
    'Bu anketi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.': 'Bu anketi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'Anket başarıyla silindi!': 'Anket başarıyla silindi!',
    'Anket silinirken bir hata oluştu. Lütfen tekrar deneyin.': 'Anket silinirken bir hata oluştu. Lütfen tekrar deneyin.',
    'Resim yüklenirken bir hata oluştu': 'Resim yüklenirken bir hata oluştu',
    'Anket resmi kaldırıldı': 'Anket resmi kaldırıldı',
    
    // Son Formlar bölümü
    'Latest Forms': 'Son Formlar',
    'All': 'Tümü',
    'Last 7 days': 'Son 7 gün',
    'Last 30 days': 'Son 30 gün',
    'responses': 'yanıt',
    
    // Trends bölümü
    'Trend Anketler': 'Trend Anketler',
    'Büyüme': 'Büyüme',
    'Uzaktan Çalışma Deneyimi': 'Uzaktan Çalışma Deneyimi',
    'Sürdürülebilir Yaşam': 'Sürdürülebilir Yaşam',
    'Dijital Dönüşüm': 'Dijital Dönüşüm'
  },
  en: {
    // Ana sayfa
    'Anketlerinizi AI ile Güçlendirin': 'Empower Your Surveys with AI',
    'Profesyonel anket oluşturucu ile benzersiz sorular hazırlayın, trend analizi yapın ve daha fazla yanıt alın.': 'Create unique questions with professional survey builder, perform trend analysis and get more responses',
    'Şablonlar': 'Templates',
    'Trendler': 'Trends',
    'Yeni bir form hazırlamaya başlayın': 'Start preparing a new form',
    'Boş Form': 'Empty Form',
    'Sıfırdan yeni bir form oluşturun': 'Create a new form from scratch',
    'AI Destekli': 'AI Supported',
    'AI Oluşturucu': 'AI Creator',
    'Yapay zeka ile otomatik oluşturun': 'Create automatically with artificial intelligence',
    'Akıllı Öneriler': 'Smart Suggestions',
    'Hazır şablonlar ile hızlıca başlayın': 'Start quickly with ready-made templates',
    'Kullan': 'Use',
    'Popüler': 'Popular',
    'Kolay': 'Easy',
    'Orta': 'Medium',
    'Zor': 'Hard',
    '2 dk': '2 min',
    '3 dk': '3 min',
    '4 dk': '4 min',
    '5 dk': '5 min',
    'İletişim Bilgileri': 'Contact Information',
    'Etkinlik LCV Formu': 'Event RSVP Form',
    'Parti Davetiyesi': 'Party Invitation',
    'Tişört İstek Formu': 'T-Shirt Request Form',
    'Etkinlik Kayıt Formu': 'Event Registration Form',
    
    // Navbar
    'Ana Sayfa': 'Home',
    'Anketlerim': 'My Forms',
    'Yeni Anket': 'New Form',

    'Çıkış Yap': 'Logout',
    'Kayıt Ol': 'Register',
    'Giriş Yap': 'Login',
    'Formlar': 'Forms',
    'Takvim': 'Calendar',
    'Bugün': 'Today',
    'Yarın': 'Tomorrow',
    'Henüz etkinlik yok': 'No events yet',
    'Yeni Etkinlik Ekle': 'Add New Event',
    'Etkinlik Adı': 'Event Name',
    'Etkinlik adını girin': 'Enter event name',
    'Tarih': 'Date',
    'Başlangıç Saati': 'Start Time',
    'Bitiş Saati': 'End Time',
    'Açıklama': 'Description',
    'Etkinlik açıklaması': 'Event description',
    'İptal': 'Cancel',
    'Etkinlik Ekle': 'Add Event',
    
    // Ayarlar
    'Ayarlar': 'Settings',
    'Genel': 'General',
    'Bildirimler': 'Notifications',
    'Gizlilik': 'Privacy',
    'Güvenlik': 'Security',
    'Profil Bilgileri': 'Profile Information',
    'Ad': 'First Name',
    'Soyad': 'Last Name',
    'E-posta': 'Email',
    'Bildirim Ayarları': 'Notification Settings',
    'E-posta Bildirimleri': 'Email Notifications',
    'Form yanıtları ve güncellemeler için': 'For form responses and updates',
    'Haftalık Raporlar': 'Weekly Reports',
    'Form performans özetleri': 'Form performance summaries',
    'Gizlilik Ayarları': 'Privacy Settings',
    'Veri Analizi': 'Data Analytics',
    'Anonim kullanım verilerini topla': 'Collect anonymous usage data',
    'Üçüncü Taraf Entegrasyonları': 'Third Party Integrations',
    'Jira, Trello gibi servisler': 'Services like Jira, Trello',
    'Güvenlik Ayarları': 'Security Settings',
    'Şifre Değiştir': 'Change Password',
    'Mevcut şifre': 'Current Password',
    'Yeni şifre': 'New Password',
    'Yeni şifre (tekrar)': 'New Password (repeat)',
    'Şifreyi Güncelle': 'Update Password',
    'İki Faktörlü Doğrulama': 'Two Factor Authentication',
    'Ek güvenlik için SMS veya uygulama kodu': 'SMS or app code for additional security',
    'Değişiklikleri Kaydet': 'Save Changes',
    'Hesabı Sil': 'Delete Account',
    'Kaydediliyor...': 'Saving...',
    'Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.': 'This action cannot be undone. All your data will be permanently deleted.',
    
    // Admin
    'Admin': 'Admin',
    'Admin E-posta': 'Admin Email',
    'Admin Şifre': 'Admin Password',
    'Admin Girişi': 'Admin Login',
    'Admin Girişi Yapılıyor...': 'Admin Login in Progress...',
            'Admin girişi başarısız! E-posta veya şifre hatalı.': 'Admin login failed! Email or password incorrect.',
        'Loglar': 'Logs',
    
    // Son Formlar bölümü
    'Latest Forms': 'Latest Forms',
    'All': 'All',
    'Last 7 days': 'Last 7 days',
    'Last 30 days': 'Last 30 days',
    'responses': 'responses',
    'Active': 'Active',
    
    // Form Builder
    'Form Oluşturucu': 'Form Builder',
    'Form Builder': 'Form Builder',
    'Form Başlığı': 'Form Title',
    'Form açıklaması': 'Form description',
    'Form description...': 'Form description...',
    'Form title...': 'Form title...',
    'Soru Ekle': 'Add Question',
    'Question Types': 'Question Types',
    'Add your first question': 'Add your first question',
    'Start by selecting one of the question types on the left': 'Start by selecting one of the question types on the left',
    'Survey Image': 'Survey Image',
    'Saving...': 'Saving...',
    'Form title is required': 'Form title is required',
    'Form Ayarları': 'Form Settings',
    'Durum': 'Status',
    'Etiketler': 'Tags',
    'Yeni etiket ekle...': 'Add new tag...',
    'Ekle': 'Add',
    'Anonim yanıtlara izin ver': 'Allow anonymous responses',
    'İlerleme çubuğunu göster': 'Show progress bar',
    'Çoklu yanıtlara izin ver': 'Allow multiple responses',
    'Formu yayınlayın': 'Publish Form',
    'Katılımcılar': 'Participants',
    'Bağlantıya sahip olan herkes': 'Anyone with the link',
    'Kopyalandı': 'Copied',
    'Form Önizleme': 'Form Preview',
    'Henüz soru eklenmemiş': 'No questions added yet',
    'Yanıtınızı yazın...': 'Write your answer...',
    'Seçenek seçin...': 'Select an option...',
    'Kaydet': 'Save',
    'Önizle': 'Preview',
    'Yayınla': 'Publish',
    
    // Auth
    'Beni Hatırla': 'Remember Me',
    'Şifremi Unuttum': 'Forgot Password',
    'Hesabınız yok mu?': 'Don\'t have an account?',
    'Zaten hesabınız var mı?': 'Already have an account?',
    'Şifre (tekrar)': 'Password (repeat)',
    'Şifreler eşleşmiyor!': 'Passwords don\'t match!',
    'Şifreler eşleşmiyor': 'Passwords don\'t match',
    
    // Login/Register specific
    'login': 'LOGIN',
    'signup': 'SIGN UP',
    'email': 'Email Address',
    'emailPlaceholder': 'Enter your email address',
    'password': 'Password',
    'passwordPlaceholder': 'Enter your password',
    'loggingIn': 'Logging In...',
    'or': 'or',
    'googleLogin': 'LOGIN WITH GOOGLE',
    'trelloLogin': 'LOGIN WITH TRELLO',
    'jiraLogin': 'LOGIN WITH JIRA',
    'personalInfo': 'Personal Information',
    'name': 'First Name',
    'namePlaceholder': 'Enter your first name',
    'surname': 'Last Name',
    'surnamePlaceholder': 'Enter your last name',
    'age': 'Age',
    'agePlaceholder': 'Enter your age',
    'passwordConfirm': 'Confirm Password',
    'passwordConfirmPlaceholder': 'Re-enter your password',
    'passwordsMatch': 'Passwords match',
    'passwordsDoNotMatch': 'Passwords do not match',
    'passwordMinLength': 'At least 8 characters',
    'passwordAtLeastOneNumber': 'At least 1 number',
    'passwordAtLeastOneSpecialChar': 'At least 1 special character',
    'addressInfo': 'Address Information',
    'city': 'City',
    'selectCity': 'Select city',
    'district': 'District',
    'selectDistrict': 'Select district',
    'bucakNahiye': 'Bucak/Nahiye',
    'selectBucakNahiye': 'Select bucak/nahiye',
    'neighbourhood': 'Neighbourhood',
    'selectNeighbourhood': 'Select neighbourhood',
    'detailedAddress': 'Detailed Address',
    'addressDetailsPlaceholder': 'Enter street, building no, floor, apartment no etc. details',
    'creatingAccount': 'Creating Account...',
    'createAccount': 'CREATE ACCOUNT',
    'forgotPassword': 'Forgot Password',
    'alreadyHaveAccount': 'Already have an account?',
    
    // Common
    'Yükleniyor...': 'Loading...',
    'Hata': 'Error',
    'Başarılı': 'Success',
    'Uyarı': 'Warning',
    'Bilgi': 'Info',
    'Tamam': 'OK',
    'Kapat': 'Close',
    'Evet': 'Yes',
    'Hayır': 'No',
    'Sil': 'Delete',
    'Düzenle': 'Edit',
    'Kopyala': 'Copy',
    'Paylaş': 'Share',
    'İndir': 'Download',
    'Yazdır': 'Print',
    'Ara': 'Search',
    'Filtrele': 'Filter',
    'Sırala': 'Sort',
    'Temizle': 'Clear',
    'Uygula': 'Apply',
    'Sıfırla': 'Reset',
    'Geri': 'Back',
    'İleri': 'Next',
    'Son': 'Last',
    'İlk': 'First',
    'Önceki': 'Previous',
    'Sonraki': 'Next',
    'Sayfa': 'Page',
    'Toplam': 'Total',
    'Göster': 'Show',
    'Kayıt': 'Record',
    'Saat': 'Time',
    'Tip': 'Type',
    'Detay': 'Detail',
    'Özet': 'Summary',
    'Rapor': 'Report',
    'İstatistik': 'Statistics',
    'Grafik': 'Chart',
    'Tablo': 'Table',
    'Liste': 'List',
    'Grid': 'Grid',
    'Kart': 'Card',
    'Modal': 'Modal',
    'Dropdown': 'Dropdown',
    'Tooltip': 'Tooltip',
    'Alert': 'Alert',
    'Notification': 'Notification',
    'Toast': 'Toast',
    'Badge': 'Badge',
    'Avatar': 'Avatar',
    'Button': 'Button',
    'Input': 'Input',
    'Select': 'Select',
    'Checkbox': 'Checkbox',
    'Radio': 'Radio',
    'Switch': 'Switch',
    'Slider': 'Slider',
    'Progress': 'Progress',
    'Spinner': 'Spinner',
    'Skeleton': 'Skeleton',
    'Divider': 'Divider',
    'Space': 'Space',
    'Row': 'Row',
    'Col': 'Col',
    'Container': 'Container',
    'Header': 'Header',
    'Footer': 'Footer',
    'Sidebar': 'Sidebar',
    'Content': 'Content',
    'Main': 'Main',
    'Section': 'Section',
    'Article': 'Article',
    'Aside': 'Aside',
    'Nav': 'Nav',
    'Menu': 'Menu',
    'Breadcrumb': 'Breadcrumb',
    'Pagination': 'Pagination',
    'Steps': 'Steps',
    'Tabs': 'Tabs',
    'Accordion': 'Accordion',
    'Collapse': 'Collapse',
    'Timeline': 'Timeline',
    'Tree': 'Tree',
    'Transfer': 'Transfer',
    'Upload': 'Upload',
    'Rate': 'Rate',
    'ColorPicker': 'ColorPicker',
    'DatePicker': 'DatePicker',
    'TimePicker': 'TimePicker',
    'Calendar': 'Calendar',
    'Form': 'Form',
    'Table': 'Table',
    'List': 'List',
    'Layout': 'Layout',
    'Navigation': 'Navigation',
    'Feedback': 'Feedback',
    'Data Entry': 'Data Entry',
    'Data Display': 'Data Display',
    'General': 'General',
    'Other': 'Other',
    // Forms sayfası
    'My Forms': 'My Forms',
    'Anket yönetimi ve takibi': 'Survey management and tracking',
    'Anket ara...': 'Search surveys...',
    'Yenile': 'Refresh',
    'Survey': 'Survey',
    'Status': 'Status',
    'Category': 'Category',
    'Responses': 'Responses',
    'Last Update': 'Last Update',
    'Actions': 'Actions',
    'Aktif': 'Active',
    'Taslak': 'Draft',
    'Arşivlenmiş': 'Archived',
    'Bilinmiyor': 'Unknown',
    'Ürün': 'Product',
    'Müşteri': 'Customer',
    'İnsan Kaynakları': 'Human Resources',
    'Eğitim': 'Education',
    'Pazarlama': 'Marketing',
    'Teknoloji': 'Technology',
    'Yanıt': 'Response',
    'Görüntü': 'View',
    'Tamamlanma': 'Completion',
    'soru': 'question',
    'Bu anketi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.': 'Are you sure you want to delete this survey? This action cannot be undone.',
    'Anket başarıyla silindi!': 'Survey deleted successfully!',
    'Anket silinirken bir hata oluştu. Lütfen tekrar deneyin.': 'An error occurred while deleting the survey. Please try again.',
    'Resim yüklenirken bir hata oluştu': 'An error occurred while uploading the image',
    'Anket resmi kaldırıldı': 'Survey image removed',
    
    // Trends section
    'Trend Anketler': 'Trend Surveys',
    'Büyüme': 'Growth',
    'Uzaktan Çalışma Deneyimi': 'Remote Work Experience',
    'Sürdürülebilir Yaşam': 'Sustainable Living',
    'Dijital Dönüşüm': 'Digital Transformation',
    
    // Question Types
    'Short Answer': 'Short Answer',
    'Paragraph': 'Paragraph',
    'Multiple Choice': 'Multiple Choice',
    'Multiple Select': 'Multiple Select',
    'Dropdown List': 'Dropdown List',
    'Rating': 'Rating',
    'Date Question': 'Date',
    'Location': 'Location',
    'Phone': 'Phone',
    'Email Question': 'Email',
    'Full Name': 'Full Name'
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // LocalStorage'dan dil tercihini al
    const savedLanguage = localStorage.getItem('language') as Language
    return savedLanguage || 'tr'
  })

  // Dil değiştiğinde localStorage'a kaydet
  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
    
    // Tüm sayfaya dil değişikliği event'i gönder
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { language } }))
  }, [language])

  // Çeviri fonksiyonu
  const t = (key: string): string => {
    const currentTranslations = translations[language] || translations['tr']
    return currentTranslations[key] || key
  }

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    isEnglish: language === 'en'
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
